force-app/main/default/objects/Campaign/fields/ContactSite__c.field-meta.xml
<CustomField>
    <fullName>ContactSite__c</fullName>
    <description>The Contact Site for the Campaign, unique to the Campaign.</description>
    <inlineHelpText>The Contact Site for the Campaign, unique to the Campaign.</inlineHelpText>
    <label>Contact Site</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program to which this Campaign relates.</description>
    <inlineHelpText>The Program to which this Campaign relates.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>ProgramCampaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/ConsentTransaction__c.object-meta.xml
<CustomObject>
    <description>Logs when an end subscriber, agent, or automation explicitly subscribes (opts in) or unsubscribes (opts out) a constituent in Salesforce.</description>
    <label>Consent Transaction</label>
    <nameField>
        <displayFormat>CT-{00000000}</displayFormat>
        <label>Consent Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConsentTransaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related Contact for this Consent Transaction, if applicable.</description>
    <inlineHelpText>The related Contact for this Consent Transaction, if applicable.</inlineHelpText>
    <label>Client (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/ContactSite__c.field-meta.xml
<CustomField>
    <fullName>ContactSite__c</fullName>
    <description>The Contact Site (origin) of this request, to help with matching to a Campaign and Campaign Member.</description>
    <inlineHelpText>The Contact Site (origin) of this request, to help with matching to a Campaign and Campaign Member.</inlineHelpText>
    <label>Contact Site</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Lead for this Consent Transaction, if applicable.</description>
    <inlineHelpText>Related Lead for this Consent Transaction, if applicable.</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Program related to the Consent Transaction.</description>
    <inlineHelpText>Program related to the Consent Transaction.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Indicates who processed the Consent Transaction.</description>
    <inlineHelpText>Indicates who processed the Consent Transaction.</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Web Form</fullName>
            </value>
            <value>
                <fullName>Subscriber</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates whether the consent transaction represents an opt-in or an unsubscribe event.</description>
    <inlineHelpText>Indicates whether the consent transaction represents an opt-in or an unsubscribe event.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opt-in</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConsentTransactionRLControllerTest.cls
/**
 * Created by joshlequire1 on 10/5/22.
 */

@IsTest
private class ConsentTransactionRLControllerTest {

    @TestSetup
    static void createTestData() {
        TestDataFactory.createCampaignMemberHarness();
    }

    @IsTest
    static void testGetConsentTransactionsForCampaignMember() {
        Campaign testCampaign = [SELECT Id, Program__c FROM Campaign WHERE Name = 'Test Campaign'][0];

        Lead testLead = new Lead();
        CampaignMember testLeadCM = [SELECT Id, LeadId FROM CampaignMember WHERE LeadId != NULL LIMIT 1][0];
        testLead.Id = testLeadCM.LeadId;
        Id leadCMId = testLeadCM.Id;

        Contact testContact = new Contact();
        CampaignMember testContactCM = [SELECT Id, ContactId FROM CampaignMember WHERE ContactId != NULL LIMIT 1][0];
        testContact.Id = testContactCM.ContactId;
        Id contactCMId = testContactCM.Id;

        Test.startTest();

        List<ConsentTransaction__c> newCTs = new List<ConsentTransaction__c>{
                new ConsentTransaction__c(
                        Contact__c = testContact.Id,
                        CurrencyIsoCode = CONSTANTS.CURRENCY_ISO_CODE_USD,
                        Source__c = CONSTANTS.CONSENT_TRANSACTION_SOURCE_WEBFORM,
                        ContactSite__c = CONSTANTS.CAMPAIGN_CONTACT_SITE_TEST_VALUE,
                        Program__c = testCampaign.Program__c,
                        Type__c = CONSTANTS.CONSENT_TRANSACTION_TYPE_OPTIN
                ),
                new ConsentTransaction__c(
                        Lead__c = testLead.Id,
                        CurrencyIsoCode = CONSTANTS.CURRENCY_ISO_CODE_USD,
                        Source__c = CONSTANTS.CONSENT_TRANSACTION_SOURCE_WEBFORM,
                        ContactSite__c = CONSTANTS.CAMPAIGN_CONTACT_SITE_TEST_VALUE,
                        Program__c = testCampaign.Program__c,
                        Type__c = CONSTANTS.CONSENT_TRANSACTION_TYPE_OPTIN
                )
        };

        Utility.processRecords(newCTs, 'insert');

        ConsentTransaction__c contactUnsubscribeCT = new ConsentTransaction__c(
                Contact__c = testContact.Id,
                CurrencyIsoCode = CONSTANTS.CURRENCY_ISO_CODE_USD,
                Source__c = CONSTANTS.CONSENT_TRANSACTION_SOURCE_AGENT,
                Program__c = testCampaign.Program__c,
                Type__c = CONSTANTS.CONSENT_TRANSACTION_TYPE_UNSUBSCRIBE
        );

        Utility.processRecords(contactUnsubscribeCT, 'insert');

        Test.stopTest();

        // Test Lead CM related CTs
        List<ConsentTransaction__c> leadCMCTs = ConsentTransactionRelatedListController.getConsentTransactionsForCampaignMember(leadCMId);
        System.assert(leadCMCTs.size() == 1);

        // Test Contact CM related CTs
        List<ConsentTransaction__c> contactCMCTs = ConsentTransactionRelatedListController.getConsentTransactionsForCampaignMember(contactCMId);
        System.debug(contactCMCTs.size());
        System.assert(contactCMCTs.size() == 2);

    }
}