force-app/main/default/objects/Campaign/fields/ContactSite__c.field-meta.xml
<CustomField>
    <fullName>ContactSite__c</fullName>
    <description>The Contact Site for the Campaign, unique to the Campaign.</description>
    <inlineHelpText>The Contact Site for the Campaign, unique to the Campaign.</inlineHelpText>
    <label>Contact Site</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program to which this Campaign relates.</description>
    <inlineHelpText>The Program to which this Campaign relates.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>ProgramCampaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CampaignSelector.cls
/**
 * Created by joshlequire1 on 9/20/22.
 */

public without sharing class CampaignSelector {

    public static Campaign getCampaignByContactSite(String contactSite){
        Campaign cpgn = [SELECT Id, Program__c FROM Campaign WHERE ContactSite__c = :contactSite AND Program__c != NULL AND IsActive = TRUE AND Type = 'Email' ORDER BY CreatedDate DESC LIMIT 1][0];

        return cpgn;
    }

    public static List<Campaign> getCampaignsByProgramIds (Set<Id> programIds){
        List<Campaign> cpgns = [SELECT Id, Program__c FROM Campaign WHERE Program__c IN :programIds];

        return cpgns;
    }

}