force-app/main/default/objects/Campaign/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program to which this Campaign relates.</description>
    <inlineHelpText>The Program to which this Campaign relates.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>ProgramCampaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/ConsentTransaction__c.object-meta.xml
<CustomObject>
    <description>Logs when an end subscriber, agent, or automation explicitly subscribes (opts in) or unsubscribes (opts out) a constituent in Salesforce.</description>
    <label>Consent Transaction</label>
    <nameField>
        <displayFormat>CT-{00000000}</displayFormat>
        <label>Consent Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConsentTransaction__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Program related to the Consent Transaction.</description>
    <inlineHelpText>Program related to the Consent Transaction.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CONSTANTS.cls
/**
 * Created by joshlequire1 on 9/20/22.
 */

public without sharing class CONSTANTS {

    // _global (all)
    public static final String CURRENCY_ISO_CODE_USD = 'USD';

    // Account
    public static final Id ACCOUNT_RECORDTYPE_PERSONACCOUNT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();

    // Campaign
    public static final Id CAMPAIGN_RECORDTYPE_OTHER = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Other').getRecordTypeId();
    public static final String CAMPAIGN_CONTACT_SITE_TEST_VALUE = 'motogppremier.com';

    // Campaign Member

    // ConsentTransaction__c
    public static final String CONSENT_TRANSACTION_TYPE_OPTIN = 'Opt-in';
    public static final String CONSENT_TRANSACTION_TYPE_UNSUBSCRIBE = 'Unsubscribe';
    public static final String CONSENT_TRANSACTION_SOURCE_WEBFORM = 'Web Form';
    public static final String CONSENT_TRANSACTION_SOURCE_AGENT = 'Agent';

    // Lead
    public static final Id LEAD_RECORDTYPE_STANDARD = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Standard').getRecordTypeId();

    // Program__c
    public static final String PROGRAM_CONTACT_SITE_PICKLIST_VALUE = 'barrettjacksonvip.com';

}