force-app/main/default/objects/Campaign/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program to which this Campaign relates.</description>
    <inlineHelpText>The Program to which this Campaign relates.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>ProgramCampaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/ConsentTransaction__c.object-meta.xml
<CustomObject>
    <description>Logs when an end subscriber, agent, or automation explicitly subscribes (opts in) or unsubscribes (opts out) a constituent in Salesforce.</description>
    <label>Consent Transaction</label>
    <nameField>
        <displayFormat>CT-{00000000}</displayFormat>
        <label>Consent Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConsentTransaction__c/fields/CampaignMemberId__c.field-meta.xml
<CustomField>
    <fullName>CampaignMemberId__c</fullName>
    <description>Links the Info Request to a Campaign Member, if one is matched. This is a text value, not a lookup, as Campaign Member lookups are not available currently on the platform.</description>
    <inlineHelpText>Links the Info Request to a Campaign Member, if one is matched.</inlineHelpText>
    <label>Campaign Member Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related Contact for this Consent Transaction, if applicable.</description>
    <inlineHelpText>The related Contact for this Consent Transaction, if applicable.</inlineHelpText>
    <label>Client (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Lead for this Consent Transaction, if applicable.</description>
    <inlineHelpText>Related Lead for this Consent Transaction, if applicable.</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Program related to the Consent Transaction.</description>
    <inlineHelpText>Program related to the Consent Transaction.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ConsentTransactionTriggerHandler.cls
/**
 * Created by joshlequire1 on 9/20/22.
 */

public without sharing class ConsentTransactionTriggerHandler {

    public static void processCampaignMemberRelationships(List<ConsentTransaction__c> newCTs) {
        Set<Id> programIds = new Set<Id>();
        List<ConsentTransaction__c> ctUpdates = new List<ConsentTransaction__c>();
        Map<Id, Campaign> programIdsToCampaigns = new Map<Id, Campaign>();
        Map<Id, ConsentTransaction__c> leadCTsToProcess = new Map<Id, ConsentTransaction__c>();
        Map<Id, ConsentTransaction__c> contactCTsToProcess = new Map<Id, ConsentTransaction__c>();
        Set<Id> matchedCTsInCMs = new Set<Id>();
        List<CampaignMember> newCMs = new List<CampaignMember>();

        for (ConsentTransaction__c ct : newCTs) {
            if (ct.Program__c != null) {
                programIds.add(ct.Program__c);
            }

            if (ct.Contact__c != null) {
                contactCTsToProcess.put(ct.Contact__c, ct);
            }

            if (ct.Lead__c != null) {
                leadCTsToProcess.put(ct.Lead__c, ct);
            }
        }

        if (programIds.size() > 0) {

            // get Campaigns for Program Ids
            for (Campaign cp : CampaignSelector.getCampaignsByProgramIds(programIds)) {
                programIdsToCampaigns.put(cp.Program__c, cp);
            }

            // Get matched Campaign Members for this list of CTs
            for (CampaignMember cm : CampaignMemberSelector.getCampaignMembersForProgramIds(programIds, leadCTsToProcess.keySet(), contactCTsToProcess.keySet())) {
                ConsentTransaction__c ctUpdate = new ConsentTransaction__c();

                if (cm.ContactId != null) {
                    ctUpdate.Id = contactCTsToProcess.get(cm.ContactId).Id;
                    matchedCTsInCMs.add(ctUpdate.Id);
                    ctUpdate.CampaignMemberId__c = cm.Id;
                    ctUpdates.add(ctUpdate);
                }

                if (cm.LeadId != null) {
                    ctUpdate.Id = leadCTsToProcess.get(cm.LeadId).Id;
                    matchedCTsInCMs.add(ctUpdate.Id);
                    ctUpdate.CampaignMemberId__c = cm.Id;
                    ctUpdates.add(ctUpdate);
                }

            }

            // Create new Campaign members for CTs that were not matched
            for (ConsentTransaction__c ct : newCTs) {
                if (!matchedCTsInCMs.contains(ct.Id)) {
                    CampaignMember newCM = new CampaignMember();
                    newCM.CampaignId = programIdsToCampaigns.get(ct.Program__c).Id;

                    if (ct.Contact__c != null) {
                        newCM.ContactId = ct.Contact__c;
                    }

                    else if (ct.Lead__c != null) {
                        newCM.LeadId = ct.Lead__c;
                    }

                    newCMs.add(newCM);

                }
            }

            // Run the DML Calls

            try {
                if (ctUpdates.size() > 0) {
                    update ctUpdates;
                }

                if (newCMs.size() > 0) {
                    insert newCMs;
                }
            } catch (DmlException e) {
                System.debug('Error occurred: ' + e.getMessage() + e.getCause());
            }


        }

    }


}