force-app/main/default/objects/ConsentTransaction__c/ConsentTransaction__c.object-meta.xml
<CustomObject>
    <description>Logs when an end subscriber, agent, or automation explicitly subscribes (opts in) or unsubscribes (opts out) a constituent in Salesforce.</description>
    <label>Consent Transaction</label>
    <nameField>
        <displayFormat>CT-{00000000}</displayFormat>
        <label>Consent Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConsentTransaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related Contact for this Consent Transaction, if applicable.</description>
    <inlineHelpText>The related Contact for this Consent Transaction, if applicable.</inlineHelpText>
    <label>Client (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/ContactSite__c.field-meta.xml
<CustomField>
    <fullName>ContactSite__c</fullName>
    <description>The Contact Site (origin) of this request, to help with matching to a Campaign and Campaign Member.</description>
    <inlineHelpText>The Contact Site (origin) of this request, to help with matching to a Campaign and Campaign Member.</inlineHelpText>
    <label>Contact Site</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Lead for this Consent Transaction, if applicable.</description>
    <inlineHelpText>Related Lead for this Consent Transaction, if applicable.</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Program related to the Consent Transaction.</description>
    <inlineHelpText>Program related to the Consent Transaction.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/QNGInfoRequest__c.field-meta.xml
<CustomField>
    <fullName>QNGInfoRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship of this Consent Transaction to an Info Request, if applicable.</description>
    <inlineHelpText>Relationship of this Consent Transaction to an Info Request, if applicable.</inlineHelpText>
    <label>Info Request (QNG)</label>
    <referenceTo>QNG_Info_Request__c</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Indicates who processed the Consent Transaction.</description>
    <inlineHelpText>Indicates who processed the Consent Transaction.</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Web Form</fullName>
            </value>
            <value>
                <fullName>Subscriber</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates whether the consent transaction represents an opt-in or an unsubscribe event.</description>
    <inlineHelpText>Indicates whether the consent transaction represents an opt-in or an unsubscribe event.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opt-in</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConsentTransactionService.cls
/**
 * Created by joshlequire1 on 9/20/22.
 */

public with sharing class ConsentTransactionService {

    public static ConsentTransaction__c createConsentTransactionFromInfoRequest(QNG_Info_Request__c infoRec, String ctType) {

        ConsentTransaction__c newCT = new ConsentTransaction__c();

        newCT.Program__c = CampaignSelector.getCampaignByContactSite(infoRec.Contact_Site__c)?.Program__c;

        newCT.Contact__c = infoRec.Contact__c;
        newCT.CurrencyIsoCode = 'USD';
        newCT.QNGInfoRequest__c = infoRec.Id;
        newCT.Lead__c = infoRec.Lead__c;
        newCT.Source__c = 'Web Form';
        newCT.ContactSite__c = infoRec.Contact_Site__c;
        newCT.Type__c = ctType;

        insert newCT;

        return newCT;

    }

}