force-app/main/default/objects/ConsentTransaction__c/ConsentTransaction__c.object-meta.xml
<CustomObject>
    <description>Logs when an end subscriber, agent, or automation explicitly subscribes (opts in) or unsubscribes (opts out) a constituent in Salesforce.</description>
    <label>Consent Transaction</label>
    <nameField>
        <displayFormat>CT-{00000000}</displayFormat>
        <label>Consent Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConsentTransaction__c/fields/CampaignMemberId__c.field-meta.xml
<CustomField>
    <fullName>CampaignMemberId__c</fullName>
    <description>Links the Info Request to a Campaign Member, if one is matched. This is a text value, not a lookup, as Campaign Member lookups are not available currently on the platform.</description>
    <inlineHelpText>Links the Info Request to a Campaign Member, if one is matched.</inlineHelpText>
    <label>Campaign Member Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related Contact for this Consent Transaction, if applicable.</description>
    <inlineHelpText>The related Contact for this Consent Transaction, if applicable.</inlineHelpText>
    <label>Client (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Lead for this Consent Transaction, if applicable.</description>
    <inlineHelpText>Related Lead for this Consent Transaction, if applicable.</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/QNGInfoRequest__c.field-meta.xml
<CustomField>
    <fullName>QNGInfoRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship of this Consent Transaction to an Info Request, if applicable.</description>
    <inlineHelpText>Relationship of this Consent Transaction to an Info Request, if applicable.</inlineHelpText>
    <label>Info Request (QNG)</label>
    <referenceTo>QNG_Info_Request__c</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>ConsentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsentTransaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates whether the consent transaction represents an opt-in or an unsubscribe event.</description>
    <inlineHelpText>Indicates whether the consent transaction represents an opt-in or an unsubscribe event.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opt-in</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConsentTransactionRelatedListController.cls
/**
 * Created by joshlequire1 on 9/19/22.
 */

public with sharing class ConsentTransactionRelatedListController {

    @AuraEnabled(Cacheable=true)
    public static List<ConsentTransaction__c> getConsentTransactionsForCampaignMember(Id recordId) {
        List<ConsentTransaction__c> consentRecords = [SELECT Id, Name, Contact__r.Name, Lead__r.Name, Type__c, QNGInfoRequest__r.Name, CreatedDate FROM ConsentTransaction__c WHERE CampaignMemberId__c = :recordId ORDER BY CreatedDate DESC];

        return consentRecords;

    }

}